services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - VUE_APP_URL_BASE_API=http://localhost:5678
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=cheerio
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node
      - ./n8n/workflows:/workflows
    depends_on:
      - mongodb
      - ollama
    networks:
      - ai_net
    restart: always
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_MODELS=/models
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
      - ollama_models:/models
    networks:
      - ai_net
    restart: always
    entrypoint: ["/bin/bash", "-c", "ollama serve & sleep 5 && ollama pull mistral-nemo:latest && wait"]
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 59117:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_COLLECTION_NAME=${MONGO_DB_COLLECTION}
      - MONGO_NON_ROOT_USERNAME=${MONGO_DB_NAME}
      - MONGO_NON_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    volumes:
      - mongo_config:/data/configdb
      - mongo_data:/data/db
      - ./data/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ai_net
  nextjs:
    build:
      context: ./web-manager
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    environment: 
      - MONGODB_URI=mongodb://${MONGO_DB_NAME}:${MONGO_DB_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}
    depends_on:
      - mongodb
    networks:
      - ai_net
volumes:
  n8n_data:
  ollama_data:
  ollama_models:
  mongo_data:
  mongo_config:
networks:
  ai_net:
    driver: bridge
