sources:
  http_json:
    type: http_server
    address: 0.0.0.0:8686
    encoding: json
    cors:
      allow_origin:
        - http://localhost:3000

sinks:
  loki:
    type: loki
    inputs: [http_json]
    endpoint: http://loki:3100
    labels:
      service: "{{ service }}"
      level: "{{ level }}"
    encoding:
      codec: json
