name: GitHub Actions Tests
run-name: ${{ github.actor }}
on: [push]
jobs:
  Web-Manager-Tests:
    name: Web Manager tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm install
        working-directory: ./web-manager

      - name: Run NextJS tests
        run: npm run test
        working-directory: ./web-manager