name: GitHub Actions Tests
run-name: ${{ github.actor }}
on: [push]
jobs:
  Web-Manager-Lint:
    name: Web Manager lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./web-manager

      - name: Run ESLint
        run: npm run lint
        working-directory: ./web-manager