name: GitHub Actions Tests
run-name: ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
jobs:
  Web-Manager-Tests:
    name: Web Manager tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm install
        working-directory: ./web-manager

      - name: Run NextJS tests
        run: npm run test
        working-directory: ./web-manager

  Web-Manager-Lint:
    name: Web Manager lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./web-manager

      - name: Run ESLint
        run: npm run lint
        working-directory: ./web-manager